### ISSUE TITLE
Invalid references in generated Rust doc

### ISSUE THREAD

**Issue by tiziano88** [project-oak/oak#810]
To check locally: `cargo doc --document-private-items --no-deps`

will produce a list of warning:

<details>

```
warning: `[Runtime]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/node/mod.rs:34:67
   |
34 |     /// This method will be invoked in a blocking fashion by the [`Runtime`], therefore node
   |                                                                   ^^^^^^^^^ cannot be resolved, ignoring
   |
   = note: `#[warn(intra_doc_link_resolution_failure)]` on by default
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/runtime/mod.rs:50:26
   |
50 | /// An identifier for a [`Node`] that is opaque for type safety.
   |                          ^^^^^^ cannot be resolved, ignoring
   |
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[oak_runtime::Runtime]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/runtime/channel.rs:74:6
   |
74 | /// [`oak_runtime::Runtime`] [`oak_runtime::Runtime::channel_get_direction`].
   |      ^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
   |
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[oak_runtime::Runtime::channel_get_direction]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/runtime/channel.rs:74:31
   |
74 | /// [`oak_runtime::Runtime`] [`oak_runtime::Runtime::channel_get_direction`].
   |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
   |
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Runtime]` cannot be resolved, ignoring it.
  --> oak/server/rust/oak_runtime/src/runtime/channel.rs:82:42
   |
82 | /// be visible outside the internals of [`Runtime`].
   |                                          ^^^^^^^^^ cannot be resolved, ignoring
   |
   = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[oak_runtime::Runtime]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/channel.rs:279:10
    |
279 |     /// [`oak_runtime::Runtime`] to encode [`Channel`]s in messages.
    |          ^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:185:34
    |
185 |     /// Allow the corresponding [`Node`] to use the [`Handle`]s passed via the iterator.
    |                                  ^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:186:60
    |
186 |     /// This is achieved by adding the [`Handle`]s to the [`Node`]s [`HashMap`] of [`Handle`]s.
    |                                                            ^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[ChannelMapping::channels]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:275:58
    |
275 |     /// order to limit the scope of holding the lock on [`ChannelMapping::channels`].
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[ChannelMapping::channels]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:286:58
    |
286 |     /// order to limit the scope of holding the lock on [`ChannelMapping::channels`].
    |                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Channel]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:387:24
    |
387 |     /// Creates a new [`Channel`] and returns a `(writer handle, reader handle)` pair.
    |                        ^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[ChannelReader]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:418:69
    |
418 |     /// - If all readers are in an erroneous status, e.g. when all [`ChannelReader`]s are orphaned,
    |                                                                     ^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Messages]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:654:10
    |
654 |     /// [`Messages`] which contain [`Handle`]'s.
    |          ^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:709:19
    |
709 |     /// Remove a [`Node`] by [`NodeId`] from the [`Runtime`].
    |                   ^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[crate::node::Configuration::new_instance]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:771:34
    |
771 |     /// itself and be passed to [`crate::node::Configuration::new_instance`] to be given to a new
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

warning: `[Node::start]` cannot be resolved, ignoring it.
   --> oak/server/rust/oak_runtime/src/runtime/mod.rs:817:10
    |
817 |     /// [`Node::start`] on the instance, and finally storing a reference to the running instance
    |          ^^^^^^^^^^^^^ cannot be resolved, ignoring
    |
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
```

</details>

**Comment by tiziano88** [comment]
@rbehjati could you take a look? It would be nice to also add something to `run_tests` that would catch this in CI.

**Comment by tiziano88** [comment]
I wonder if this is still the case, I think #827 fixed at least some of those occurrences.

**Comment by rbehjati** [comment]
A few paths were still incorrect. I've created a PR (#841).
I have no idea how this could be tested. Please let me know if you have any ideas :)

**Comment by tiziano88** [comment]
No concrete ideas, but since they show up as warnings when running `cargo doc`, and I don't see a way of promoting those warnings to error, perhaps `| grep '^WARNING'` or something like that could help?

**Comment by rbehjati** [comment]
> No concrete ideas, but since they show up as warnings when running `cargo doc`, and I don't see a way of promoting those warnings to error, perhaps `| grep '^WARNING'` or something like that could help?

@tiziano88 I've added a new step to cloudbuild, which invokes this script: https://github.com/project-oak/oak/blob/c87e15ec5951843a1e8316b5bcb308aa302999a2/scripts/generate_docs#L1-L12.
I also moved the `check_formatting` step towards the end of the build steps as suggested by David: https://github.com/project-oak/oak/issues/552#issuecomment-582268894. What do you think?

**Comment by tiziano88** [comment]
I think all of these are potentially good things, but it would be easier to discuss them if they were in separate PRs, so that the conversation can focus on each aspect independently of the others, and they don't need to necessarily block each other

**Comment by tiziano88** [comment]
@rbehjati I just ran into a build failing because of some error with docs, but the logs are quite vague, would it be simple enough to also log the actual errors? Perhaps we should capture the output, and then pass it via grep, but also print it out. Do you think it's worth fixing?

```
Already have image: gcr.io/oak-ci/oak:latest
++ export RUST_LOG=info
++ RUST_LOG=info
++ readonly DOCKER_IMAGE_NAME=gcr.io/oak-ci/oak
++ DOCKER_IMAGE_NAME=gcr.io/oak-ci/oak
++ readonly SERVER_DOCKER_IMAGE_NAME=gcr.io/oak-ci/oak-server
++ SERVER_DOCKER_IMAGE_NAME=gcr.io/oak-ci/oak-server
++ readonly CACHE_DIR=bazel-cache
++ CACHE_DIR=bazel-cache
++ readonly OAK_REMOTE_CACHE_KEY=./.oak_remote_cache_key.json
++ OAK_REMOTE_CACHE_KEY=./.oak_remote_cache_key.json
++ set +o xtrace
++ declare -a bazel_build_flags
++ bazel_build_flags+=('--remote_cache=https://storage.googleapis.com/oak-bazel-cache' '--block_for_lock=false' '--show_timestamps')
++ [[ -f ./.oak_remote_cache_key.json ]]
++ bazel_build_flags+=('--remote_upload_local_results=false')
+ cargo doc --document-private-items --no-deps
+ grep --ignore-case --quiet '--regexp=^warning'
+ echo 'Warnings found when generating the docs.'
+ exit 1
Warnings found when generating the docs.
```

**Comment by rbehjati** [comment]
`cargo doc` generates too much output. I have replaced (in #852) the `--quiet` flag in `grep` with `--after-context 8` so only the warnings are printed.
